apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - infra/k8s/*
build:
  artifacts:
    # - image: us.gcr.io/utopian-bonito-411004/auth
    - image: asia-southeast2-docker.pkg.dev/utopian-bonito-411004/ticket-artifacts/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    # - image: us.gcr.io/utopian-bonito-411004/client
    - image: asia-southeast2-docker.pkg.dev/utopian-bonito-411004/ticket-artifacts/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    # - image: us.gcr.io/utopian-bonito-411004/tickets
    - image: asia-southeast2-docker.pkg.dev/utopian-bonito-411004/ticket-artifacts/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    # - image: us.gcr.io/utopian-bonito-411004/orders
    - image: asia-southeast2-docker.pkg.dev/utopian-bonito-411004/ticket-artifacts/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    # - image: us.gcr.io/utopian-bonito-411004/expiration
    - image: asia-southeast2-docker.pkg.dev/utopian-bonito-411004/ticket-artifacts/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    # - image: us.gcr.io/utopian-bonito-411004/payments
    - image: asia-southeast2-docker.pkg.dev/utopian-bonito-411004/ticket-artifacts/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
  googleCloudBuild:
    projectId: utopian-bonito-411004
