apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          # image: us.gcr.io/utopian-bonito-411004/auth
          image: asia-southeast2-docker.pkg.dev/utopian-bonito-411004/ticket-artifacts/auth
          env:
            - name: MONGO_URI
              value: mongodb://auth-mongo-srv:27017/auth # alternatively can be defined with secrets like JWT_KEY
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY # kubectl create secret generic jwt-secret --from-literal=JWT_KEY=asdf
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  type: NodePort
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
