apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          # image: us.gcr.io/utopian-bonito-411004/orders
          image: asia-southeast2-docker.pkg.dev/utopian-bonito-411004/ticket-artifacts/orders
          env:
            - name: MONGO_URI
              value: mongodb://orders-mongo-srv:27017/orders # alternatively can be defined with secrets like JWT_KEY
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY # kubectl create secret generic jwt-secret --from-literal=JWT_KEY=asdf
---
apiVersion: v1
kind: Service
metadata:
  name: orders-srv
spec:
  selector:
    app: orders
  type: NodePort
  ports:
    - name: orders
      protocol: TCP
      port: 3000
      targetPort: 3000
