name: Build and Deploy Tickets Service to GKE

on:
  push:
    branches: ["main"]
    paths: ["tickets/**"]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GAR_LOCATION: asia-southeast2
  GKE_CLUSTER: ticket-dev-sea1c
  GKE_ZONE: asia-southeast1-c
  DEPLOYMENT_NAME: gke-test
  REPOSITORY: ticket-artifacts
  IMAGE: tickets

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GKE_PROJECT }}
          install_components: 'gke-gcloud-auth-plugin'

      - name: Build and push docker image
        run: |-
          gcloud auth configure-docker asia-southeast2-docker.pkg.dev
          docker build -t asia-southeast2-docker.pkg.dev/$PROJECT_ID/ticket-artifacts/tickets:latest ./tickets
          docker push asia-southeast2-docker.pkg.dev/$PROJECT_ID/ticket-artifacts/tickets:latest

      - name: Deploy to GKE
        run: |-
          gcloud container clusters get-credentials $GKE_CLUSTER --region $GKE_ZONE
          kubectl apply -f ./infra/k8s/tickets-mongo-depl.yaml
          kubectl apply -f ./infra/k8s/tickets-depl.yaml
